name: test

on:
  push:
    branches: ['dev', 'main']
  pull_request:
    branches: ['dev', 'main']
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install
        run: pnpm install --no-frozen-lockfile 

      - name: Run test
        run: pnpm run test --run
